import unittest
from explore import cross_river


# function generated by a LLM...   https://chatgpt.com/share/67a8dd73-c1cc-8003-90c4-bddd7349f516

class TestCrossRiver(unittest.TestCase):
    
    def test_cross_river_zero_length_invalid_result(self):
        """Test that a raft with zero length returns False."""
        raft = {'length': 0, 'width': 5}
        self.assertFalse(cross_river(raft))
    
    def test_cross_river_zero_width_invalid_result(self):
        """Test that a raft with zero width returns False."""
        raft = {'length': 5, 'width': 0}
        self.assertFalse(cross_river(raft))
    
    def test_cross_river_small_raft_fell_off_result(self):
        """Test that a raft smaller than 2x2 returns False."""
        raft = {'length': 1, 'width': 1}
        self.assertFalse(cross_river(raft))
    
    def test_cross_river_large_raft_stuck_result(self):
        """Test that a raft larger than 10 in any dimension returns False."""
        raft = {'length': 11, 'width': 5}
        self.assertFalse(cross_river(raft))
    
    def test_cross_river_insufficient_volume_sank_result(self):
        """Test that a raft with volume < minimum_volume returns False."""
        raft = {'length': 4, 'width': 4}  # volume = 16 < 20
        self.assertFalse(cross_river(raft))
    
    def test_cross_river_valid_raft_success_result(self):
        """Test that a raft within valid dimensions and volume returns True."""
        raft = {'length': 5, 'width': 5}  # volume = 25 >= 20
        self.assertTrue(cross_river(raft))
    
    def test_cross_river_minimum_size_raft_sank_result(self):
        """Test that a raft with minimum valid dimensions (2x2) sinks due to insufficient volume."""
        raft = {'length': 2, 'width': 2}  # volume = 4 < 20
        self.assertFalse(cross_river(raft))
    
    def test_cross_river_maximum_size_raft_success_result(self):
        """Test that a raft with maximum valid dimensions (10x10) successfully crosses the river."""
        raft = {'length': 10, 'width': 10}  # volume = 100 >= 20
        self.assertTrue(cross_river(raft))



if __name__ == '__main__':
    unittest.main()
